### ISSUE TITLE
nxmlreader unresolved dependency issue

### ISSUE THREAD

**Issue by maxaalexeeva** [lum-ai/nxmlreader#10]
Hi @myedibleenso and @marcovzla! Is this the right place for this issue? I ended up using an older version ("ai.lum" %% "nxmlreader" % "0.1.2"), but figured I'd post it anyway for the record. Can that have been something I was doing wrong?
```
Resolving ai.lum#nxmlreader_2.12;0.1.3-SNAPSHOT ...
[warn]  module not found: ai.lum#nxmlreader_2.12;0.1.3-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/masha/.ivy2/local/ai.lum/nxmlreader_2.12/0.1.3-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/ai/lum/nxmlreader_2.12/0.1.3-SNAPSHOT/nxmlreader_2.12-0.1.3-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/masha/.sbt/preloaded/ai.lum/nxmlreader_2.12/0.1.3-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/masha/.sbt/preloaded/ai/lum/nxmlreader_2.12/0.1.3-SNAPSHOT/nxmlreader_2.12-0.1.3-SNAPSHOT.pom
[warn] ==== Typesafe Repo: tried
[warn]   http://repo.typesafe.com/typesafe/releases/ai/lum/nxmlreader_2.12/0.1.3-SNAPSHOT/nxmlreader_2.12-0.1.3-SNAPSHOT.pom
[info] Resolving jline#jline;2.14.5 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: ai.lum#nxmlreader_2.12;0.1.3-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          ai.lum:nxmlreader_2.12:0.1.3-SNAPSHOT (/home/masha/research/clint/build.sbt#L17-32)
[warn]            +- org.clulab:clint_2.12:0.0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: ai.lum#nxmlreader_2.12;0.1.3-SNAPSHOT: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1541)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1537)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1572)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1570)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1575)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1569)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1592)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1519)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1471)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: ai.lum#nxmlreader_2.12;0.1.3-SNAPSHOT: not found

```

The build file:
```
name := "clint"

version := "0.0.1-SNAPSHOT"

organization := "org.clulab"

scalaVersion := "2.12.4"

resolvers += "Typesafe Repo" at "http://repo.typesafe.com/typesafe/releases/"

scalacOptions ++= Seq(
  "-feature",
  "-unchecked",
  "-deprecation"
)

libraryDependencies ++= Seq(
  "org.scalatest" %% "scalatest" % "3.0.4" % "test",
  "org.clulab" %% "processors-main" % "7.1.0",
  "org.clulab" %% "processors-corenlp" % "7.1.0",
  "org.clulab" %% "processors-modelsmain" % "7.1.0",
  "org.clulab" %% "processors-modelscorenlp" % "7.1.0",
  "ai.lum" %% "common" % "0.0.8",
  "ai.lum" %% "nxmlreader" % "0.1.2",
  "com.typesafe.scala-logging" %% "scala-logging" % "3.9.0",
  "ch.qos.logback" % "logback-classic" % "1.2.3",
  "org.clulab" %% "processors-odin" % "7.1.0",
  //"com.mnemotix" %% "stringmetric-core" % "0.28.0-SNAPSHOT",
  "me.tongfei" % "progressbar" % "0.4.0",
  "io.spray" %%  "spray-json" % "1.3.3"
)
```
That was for the emboot project.

**Comment by myedibleenso** [comment]
@maxaalexeeva, it looks like you're trying to use a SNAPSHOT version which hasn't been published.  Try cloning this repo and running `sbt publishLocal`.

**Comment by maxaalexeeva** [comment]
@myedibleenso great! Thank you! I didn't know how to use that locally.
